[rhel-7-server-rpms]
name=rhel-7-server-rpms
baseurl=http://${bastion_public_ip}/repos/rhel-7-server-rpms
enabled=1
gpgcheck=0
[rhel-7-server-extras-rpms]
name=rhel-7-server-extras-rpms
baseurl=http://${bastion_public_ip}/repos/rhel-7-server-extras-rpms
enabled=1
gpgcheck=0
[rhel-7-server-ose-3.6-rpms]
name=rhel-7-server-ose-3.6-rpms
baseurl=http://${bastion_public_ip}/repos/rhel-7-server-ose-3.6-rpms
enabled=1
gpgcheck=0
