
# OpenShift Inventory Template.
# Note that when the infrastructure is generated by Terraform, this file is
# expanded into './inventory.cfg', based on the rules in:


# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
etcd
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

# If ansible_ssh_user is not root, ansible_become must be set to true
ansible_become=false

# Deploy OpenShift Enterprise 3.9.
openshift_deployment_type=openshift-enterprise
openshift_version= 3.9.33
openshift_enable_docker_excluder=false

# We need a wildcard DNS setup for our public access to services, fortunately
# we can use the superb xip.io to get one for free.
openshift_public_hostname=${master_hostname}
openshift_master_default_subdomain=openshift.ibm.com

# Use an htpasswd file as the indentity provider.
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_disable_check= docker_image_availability,docker_storage,memory_availability,package_availability,package_version
# Uncomment the line below to enable metrics for the cluster.
# openshift_hosted_metrics_deploy=true



[masters]
${master_hostname} openshift_hostname=${master_hostname}

# host group for etcd
[etcd]
${master_hostname} openshift_hostname=${master_hostname}

# host group for nodes, includes region info
[nodes]
${master_hostname} openshift_ip=${master_ip} openshift_hostname=${master_hostname} openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true